/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

var listController = {
    // This object acts as a controller for the list UI.
    // It implements the dataSource methods for the list.
    
    numberOfRows: function() {
        // The List calls this dataSource method to find out how many rows should be in the list.
        return cameras.length;
    },
    
    prepareRow: function(rowElement, rowIndex, templateElements) {
        // The List calls this dataSource method for every row.  templateElements contains references to all elements inside the template that have an id. We use it to fill in the text of the rowTitle element.
        if (templateElements.rowTitle) {
            templateElements.rowTitle.innerText = cameras[rowIndex].name;
        }

        // We also assign an onclick handler that will cause the browser to go to the detail page.
        var self = this;
        var handler = function() {
            var camera = cameras[rowIndex];
            detailController.setCamera(camera);
            var browser = document.getElementById('browser').object;
            // The Browser's goForward method is used to make the browser push down to a new level.  Going back to previous levels is handled automatically.
            browser.goForward(document.getElementById('detailLevel'), camera.name);
        };
        rowElement.onclick = handler;
    }
};

var detailController = {
    // This object acts as a controller for the detail UI.
    
    setCamera: function(camera) {
        this._camera = camera;
        this._representedObject = camera.name;
        var detailTitle = document.getElementById('detailTitle');
        detailTitle.innerHTML = this._camera.name;
        var detailLocation = document.getElementById('detailLocation');
        detailLocation.innerHTML = this._camera.location;
        var detailDescription = document.getElementById('detailDescription');
        detailDescription.innerHTML = "Camera data from BC Ferries";
        var detailPicture = document.getElementById('detailPicture');
        detailPicture.src = this._camera.url;
    }
    
};

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
}

// Sample data.  Some applications may have static data like this, but most will want to use information fetched remotely via XMLHttpRequest.
var cameras = [
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_hsb.jpg", name: "Horseshoe Bay 1", location: "Vancouver - outside terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_hsb.jpg", name: "Horseshoe Bay 2", location: "Vancouver - to Naniamo"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam3_hsb.jpg", name: "Horseshoe Bay 3", location: "Vancouver - to Langdale"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam4_hsb.jpg", name: "Horseshoe Bay 4", location: "Vancouver - to Bowen Island"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_tsa.jpg", name: "Tsawwassen 1", location: "Vancouver - Outside Terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_tsa.jpg", name: "Tsawwassen 2", location: "Vancouver - to Naniamo"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam3_tsa.jpg", name: "Tsawwassen 3", location: "Vancouver - to Swartz Bay"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam4_tsa.jpg", name: "Tsawwassen 4", location: "Vancouver - to Southern Gulf Islands"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_swb.jpg", name: "Swartz Bay 1", location: "Victoria - Outside Terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_swb.jpg", name: "Swartz Bay 2", location: "Victoria - to Tsawwassen"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam3_swb.jpg", name: "Swartz Bay 3", location: "Victoria - to Southern Gulf Islands"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_nan.jpg", name: "Departure Bay 1", location: "Naniamo - Outside Terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_nan.jpg", name: "Departure Bay 2", location: "Naniamo - to Departure Bay"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_duk.jpg", name: "Duke Point 1", location: "Naniamo - Outside Terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_duk.jpg", name: "Duke Point 2", location: "Naniamo - to Tsawwassen"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam1_lng.jpg", name: "Langdale 1", location: "Sunshine Coast - Outside Terminal"},
    {url:"http://orca.bcferries.com:8080/cc/data/cam2_lng.jpg", name: "Langdale 2", location: "Sunshine Coast - to Departure Bay"}
];
